name: Build Ascendara (Development)

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean electron-builder cache
        run: rm -rf ~/.cache/electron-builder/appimage

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn buildwithelectron
